services:
  mongodb:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  api-service:
    build: .
    image: bsk-api:latest
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongo-data:
